name: flutter_clean
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  injectable_generator: ^2.5.0
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - .env